/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AButton: typeof import('ant-design-vue/es')['Button']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Condition: typeof import('./components/Condition.vue')['default']
    End: typeof import('./components/End.vue')['default']
    Node: typeof import('./components/Node.vue')['default']
    PropertySidebar: typeof import('./components/PropertySidebar.vue')['default']
    ResizableSidebar: typeof import('./components/ResizableSidebar.vue')['default']
    Start: typeof import('./components/Start.vue')['default']
    ToolSidebar: typeof import('./components/ToolSidebar.vue')['default']
    X6GraphDemo: typeof import('./components/X6GraphDemo.vue')['default']
  }
}
